server:
  port: 8764
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: spring-provider-demo

management:
  endpoints:
    web:
      exposure:
        include: refresh,info,health
