server:
  port: 8762
      
spring:
  application:
    name: spring-provider-demo
  rabbitmq:
      host: 121.196.11.72
      port: 5672
      username: guest
      password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: refresh,info,health
