server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
spring:
  application:
    name: spring-provider-demo
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      
management:
  endpoints:
    web:
      exposure:
        include: *
